/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.steinko.bddwithcucumber;

import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

import bddwithcucumberapitest.Library;


public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue( classUnderTest.someLibraryMethod());
    }
}
